CREATE TABLE IF NOT EXISTS street (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    street_type VARCHAR(50) NOT NULL DEFAULT 'вулиця',
    city VARCHAR(100) NOT NULL DEFAULT 'Київ',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
